### ISSUE TITLE
[Bug] Loading .tif image produces image artifact

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaImages/Images.jl#1017] opened 2022-10-25 13:21 UTC
The original image looks like this:
![image](https://user-images.githubusercontent.com/61620837/197782461-4697d394-66b5-43e9-a8c8-a7ef1c09ddc2.png)

I then load the image with the following command:  
`Images.load(joinpath(pwd(), "above_focal_sum", "113mm.tif"))`

The resulting image looks like this (imprecise cropping, color and lines are of interest)
![image](https://user-images.githubusercontent.com/61620837/197782620-bef0a64c-94a6-47b1-a15d-aa0eda10ecdc.png)
, where the image is displayed in a pluto notebook

There is now an artifact in the image, with vertical lines across the entire thing. The artifact is very visible in a plot of the values of two slices of the image, where the RGB values have been converted to `Gray` and then to float:
![image](https://user-images.githubusercontent.com/61620837/197784018-0cdccf87-9eaf-4121-af3e-07fe287fb8c9.png)

As can be seen from the path, the image is a .tif file. The original image is grayscale, whereas the read in image has RGB values and visually a warmer tone.
The original image file can be found at https://drive.google.com/file/d/1dIhkYY5C7EumgCZaLI0TqPlorRjL1BX0/view?usp=sharing

Can anyone help me on how to correctly read the image?

**Comment by timholy** [comment] 2022-10-25 21:58
CC @tlnagy as the TIFF expert

**Comment by KronosTheLate** [comment] 2022-10-29 11:59
The fix for me ended up being using ImageMagick's `convert` function to convert the images to `.jpg`, and to load those. That worked fine. That could be a good temporary fix I suppose - at least vastly superior to a silent incorrectness bug. Something like making the `.jpg` file, loading it into Julia, and then deleting the file.

**Comment by tlnagy** [comment] 2022-11-02 17:44
Huh, initially I was worried that this was a bug in `TiffImages.jl`, but the file is LZW compressed so it hits https://github.com/tlnagy/TiffImages.jl/issues/8 (I don't yet support LZW compression), which causes `TiffImages.jl` to error out on load and then `FileIO` switches to `ImageMagick.jl` and that loads the image incorrectly. 

So this is a missing feature in `TiffImages.jl` and a bug in `ImageMagick.jl`. Your solution is a pragmatic one, but LZW support would be very nice to have in `TiffImages.jl` longer term.

**Comment by tlnagy** [comment] 2022-11-02 18:18
I don't know the `ImageMagick.jl` codebase well but my guess is that the raw type isn't properly mapped to the Julian type so not a bug in imagemagick itself, but in the Julia conversion. The bug looks like it's potentially a RGB vs RGBA problem.

**Comment by KronosTheLate** [comment] 2022-11-02 18:27
Oscar Smith said on discourse that it looked like an issue with alpha values....
So this issue should be reproduced purely in ImageMagick, and an issue should be opened up over there?

**Comment by tlnagy** [comment] 2022-11-02 18:37
> Oscar Smith said on discourse that it looked like an issue with alpha values....

Yeah, that was my guess too.

> So this issue should be reproduced purely in ImageMagick, and an issue should be opened up over there?

 I would do that (+ link to the discussion here) and close this issue.

**Comment by KronosTheLate** [comment] 2022-11-10 13:16
I made https://github.com/JuliaIO/ImageMagick.jl/issues/211.
When someone reproduces the image without Images.jl, we can close this issue.

**Comment by KronosTheLate** [comment] 2023-02-23 10:40
I more refined workaround, as I encountered this again:
```

let  #! Converting image type
    original_dir = pwd()
    input_dir = "/home/dennishb/Uni/Semester/8. Sem/Advanced Physical Optics/Lab excercise 2/Pictures"
    cd(input_dir)
    
    input_extension = ".tif"
    output_extension = ".bmp"

    files = readdir()
    input_files = filter(x->occursin(input_extension, x), files)
    filenames = getindex.(split.(input_files, '.'), 1)
    for filename in filenames
        input_filename = string(filename, input_extension)
        output_filename = string(filename, output_extension)
        isfile(output_filename)  && continue
        try
            run(`convert $input_filename $output_filename`)
            @info "Converted $filename from $input_extension to $output_extension."
        catch e
            @warn "Error occured in converting $filename from $input_extension to $output_extension.
            Continuing to next file."
        end
    end
    cd(original_dir)
end
```

**Comment by KronosTheLate** [comment] 2023-03-06 11:54
This could be related to https://github.com/tlnagy/TiffImages.jl/issues/8

**Comment by tlnagy** [comment] 2023-03-06 21:30
Yes, `TiffImages` doesn't yet support LZW compressed images so it will complain. It on my list of things to do, but I don't have the bandwidth to fix this for the next couple months at least.

**Comment by ashwani-rathee** [comment] 2023-06-15 14:13
Can this issue be moved to TiffImages.jl?

**Comment by timholy** [comment] 2023-06-15 14:21
I'm not sure you can transfer across orgs; at any rate, I don't have the requisite permissions.

**Comment by tlnagy** [comment] 2023-06-15 16:08
AFAICT this is a dupe of https://github.com/tlnagy/TiffImages.jl/issues/8 for the TiffImsges side of things. So it can be closed in lieu of that issue.

**Comment by KronosTheLate** [comment] 2023-06-15 16:42
So this is an issue with the LZW compression? Could someone download the original images (from the OP), and save them with a different compression, and verify that this is the issue?

Also, is it possible to at least make it error loudly instead of silently, by checking the compression and refusing to load LZW compressed tiff images, as a temporary "fix"?

**Comment by timholy** [comment] 2023-06-15 17:40
You might want to continue any additional conversation at https://github.com/tlnagy/TiffImages.jl/issues/8

**Closed** 2023-06-15 17:39 UTC

**Comment by KronosTheLate** [comment] 2023-06-17 08:58
The main issue here is the silent error, i.e. loading the image incorrectly and pretending everything is fine. This issue does not occur when using TiffImages directly, so the silent error part seems to be a problem with Images.jl, and not TiffImages.jl. But as recommended, I started that conversation in [this](https://github.com/tlnagy/TiffImages.jl/issues/8#issuecomment-1595677010) comment in https://github.com/tlnagy/TiffImages.jl/issues/8

**Comment by timholy** [comment] 2023-06-18 11:46
The right fix is to delete ImageMagick.jl 🙂. The ImageMagick C library has so many bugs, it's basically hopeless.

**Comment by KronosTheLate** [comment] 2023-06-18 12:21
> The right fix is to delete ImageMagick.jl

I have found ImageMagick (used from bash) quite usefull in converting between image formats. What options would you reccomend? Perhaps using Images.jl directly to load different formats, and saving them in the target format, is just as powerful?

**Comment by timholy** [comment] 2023-06-18 18:27
Images.jl has no IO. All it does is reexport FileIO. Most of the IO is from ImageIO.jl (which is itself just a bundler of more focused packages), but there are a few formats for which there is no native Julia support (nor direct wrapping of the industry-standard `lib<format>.so`) and thus ImageMagick.jl cannot yet be sunset. But if you use a format supported by a Julia package, my experience is that our implementations are almost always better (or perhaps more precisely, often better and also more readily fixable when they aren't).
