### ISSUE TITLE
Problems Saving Tifs

### ISSUE THREAD

**Issue by rand5** [JuliaImages/Images.jl#598] opened 2017-02-28 18:14 UTC
I'm having trouble saving tif images.
Here is a minimal example that works:

> `g = rand(809,809)`
> `save("Test.tif",g)`
> `G = load("Test.tif")`

Here, G is a grayscale image of type `Array{UInt8,2}` where the values are uniformly distributed (with G appearing as static).
The following does not behave as I would expect:

> `g = rand(810,810)`
> `save("Test.tif",g)`
> `G = load("Test.tif")`

In this case, G is of type `Array{UInt8,2}` and _every element is_ `0x00` (with G appearing as completely black). I can load tifs larger than 810-by-810 perfectly fine, so I suspect the issue is when saving the image.

Running the following:
> Julia Version 0.5.0
> Commit 3c9d753 (2016-09-19 18:14 UTC)
> Platform Info:
>   System: NT (x86_64-w64-mingw32)
> CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
>   WORD_SIZE: 64
>   BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
>   LAPACK: libopenblas64_
>   LIBM: libopenlibm
>   LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

and using `- Images                        0.7.0`

**Comment by timholy** [comment] 2017-03-01 03:33
You win the prize for strange bug of the week. :smile:

I can't reproduce on
```julia
julia> versioninfo()
Julia Version 0.5.1-pre+31
Commit 6a1e339* (2016-11-17 17:50 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```
I suspect it's an ImageMagick issue, though. What happens if you open `"Test.tif"` in an external (i.e., non-julia) viewer program? Is that what you tried when you said it was all black?

**Comment by rand5** [comment] 2017-03-01 14:13
Hi @timholy , yes, if "Test.tif" is 810-by-810 or more, it appears black in ImageJ and in the windows built-in image viewer-- I originally noticed the problem because the thumbnail image created by windows was not what I expected it to be.

**Comment by timholy** [comment] 2017-03-01 15:30
I suspect this is a bug in the ImageMagick C library, and since I can't reproduce it on my machine I doubt there's much I can do to help. Things I'd suggest trying include:
- see if it happens with RGB as well as grayscale
- see if it happens if you save as PNG, JPG, whatever
- see if it happens if you run the ImageMagick command line program (`convert img.png img.tif`).

**Comment by rand5** [comment] 2017-03-01 15:44
+ If I try saving the image a grayscale `.png` file I get the following fatal error: `@ error/png.c/MagickPNGErrorHandler/1630`. 

+ Saving the image as a grayscale `.jpg` does work. 

+ Saving the image as an RGB tiff seems to produce a similar error for smaller image sizes-- a 400-by-400 RGB tif appears as all black. 

For clarity, I am generating the RGB image as `g = rand(RGB{Float64},400,400)`

**Comment by timholy** [comment] 2017-03-01 15:52
Just to check, what happens if you use `rand(RGB{N0f8},400,400)`?

**Comment by rand5** [comment] 2017-03-01 17:42
@timholy, Good news-  I think I have zeroed in on the issue. I was saving the image to a drive with sufficient space for an 809-by-809 grayscale image, but insufficient space for a 810-by-810 grayscale image. The problem is resolved if I save the image to a new drive with plenty of space.  This likely explains why you were not able to reproduce the issue and explains why I was unable to properly save and load smaller RGB images. Is ImageMagick overwriting the image contents to fit the available disk space or would it be a different function/app that is doing this automatically? If it is ImageMagick doing this, it might be nice to throw a warning

**Comment by timholy** [comment] 2017-03-01 20:39
I understand why you ask that, but I think it's fair to say that the vast majority of command-line utilities don't warn on overwriting. I think that's because it's very common to have re-run scripts that overwrite the same files.

**Comment by rand5** [comment] 2017-03-01 20:56
I agree that overwriting existing files should not produce a warning. The situation here though appears to involve writing a file to a drive with insufficient space. Because there is insufficient space, the contents of the file are altered to force the file to fit the available space-- the pixel values in the image were changed to black. Overwriting is fine, but removing information from a  file as it is being saved, without a warning, seems not so nice.

**Comment by timholy** [comment] 2017-03-01 22:11
We already check to see whether ImageMagick throws an error:
https://github.com/JuliaIO/ImageMagick.jl/blob/f2c74fa77c8b29a3e8132b0ddc23a6fbbc75cf2b/src/libmagickwand.jl#L293-L297

Do you see anything else we could do?

**Comment by timholy** [comment] 2017-04-02 17:45
Since I think this is really an libmagick bug, I'm going to close this.

**Closed by timholy** 2017-04-02 17:45 UTC
