### ISSUE TITLE
Error loading images in VSCode REPL

### ISSUE THREAD

**Issue by aviks** [JuliaImages/Images.jl#912] opened 2020-09-03 15:30 UTC
```
julia> versioninfo()
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\avik\AppData\Local\Programs\Microsoft VS Code\Code.exe"
  JULIA_NUM_THREADS =
```
```
(@v1.4) pkg> st
Status `C:\Users\avik\.julia\environments\v1.4\Project.toml`
  [5ae59095] Colors v0.12.4
  [82e4d734] ImageIO v0.3.0
  [02fcd773] ImageTransformations v0.8.6
  [916415d5] Images v0.22.4
```

```
julia> using Images

julia> load("example\\baboon.png")
Errors encountered while saving nothing.
All errors:
===========================================
MethodError: no method matching save(::Base64.Base64EncodePipe, ::Array{RGB{Normed{UInt8,8}},2}, ::Pair{Symbol,ImageShow.var"#14#16"})
Closest candidates are:
  save(::IO, ::S; compression_level, compression_strategy, filters, palette) where {T, S<:Union{AbstractArray{T,3}, AbstractArray{T,2} where T}} at C:\Users\avik\.julia\packages\PNGFiles\Sgsmw\src\io.jl:289
  save(::String, ::S; compression_level, compression_strategy, filters, palette) where {T, S<:Union{AbstractArray{T,3}, AbstractArray{T,2} where T}} at C:\Users\avik\.julia\packages\PNGFiles\Sgsmw\src\io.jl:257
===========================================
ArgumentError: Package ImageMagick not found in current path:
- Run `import Pkg; Pkg.add("ImageMagick")` to install the ImageMagick package.

===========================================
MethodError: no method matching save(::FileIO.Stream{FileIO.DataFormat{:PNG},Base64.Base64EncodePipe}, ::Array{RGB{Normed{UInt8,8}},2}; mapi=ImageShow.var"#14#16"())
Closest candidates are:
  save(::FileIO.File{FileIO.DataFormat{:PNG}}, ::Any) at C:\Users\avik\.julia\packages\FileIO\wN5rD\src\mimesave.jl:6 got unsupported keyword argument "mapi"
  save(::FileIO.File{FileIO.DataFormat{:SVG}}, ::Any) at C:\Users\avik\.julia\packages\FileIO\wN5rD\src\mimesave.jl:16 got unsupported keyword argument "mapi"
  save(::FileIO.File{FileIO.DataFormat{:PDF}}, ::Any) at C:\Users\avik\.julia\packages\FileIO\wN5rD\src\mimesave.jl:26 got unsupported keyword argument "mapi"
  ...
===========================================

Fatal error:
Error showing value of type Array{RGB{Normed{UInt8,8}},2}:
ERROR: MethodError: no method matching save(::Base64.Base64EncodePipe, ::Array{RGB{Normed{UInt8,8}},2}, ::Pair{Symbol,ImageShow.var"#14#16"})
Closest candidates are:
  save(::IO, ::S; compression_level, compression_strategy, filters, palette) where {T, S<:Union{AbstractArray{T,3}, AbstractArray{T,2} where T}} at C:\Users\avik\.julia\packages\PNGFiles\Sgsmw\src\io.jl:289
  save(::String, ::S; compression_level, compression_strategy, filters, palette) where {T, S<:Union{AbstractArray{T,3}, AbstractArray{T,2} where T}} at C:\Users\avik\.julia\packages\PNGFiles\Sgsmw\src\io.jl:257
Stacktrace:
 [1] handle_error(::MethodError, ::FileIO.Stream{FileIO.DataFormat{:PNG},Base64.Base64EncodePipe}) at C:\Users\avik\.julia\packages\FileIO\wN5rD\src\error_handling.jl:82
 [2] handle_exceptions(::Array{Any,1}, ::String) at C:\Users\avik\.julia\packages\FileIO\wN5rD\src\error_handling.jl:77
 [3] save(::FileIO.Formatted, ::Any; options::Base.Iterators.Pairs{Symbol,ImageShow.var"#14#16",Tuple{Symbol},NamedTuple{(:mapi,),Tuple{ImageShow.var"#14#16"}}}) at C:\Users\avik\.julia\packages\FileIO\wN5rD\src\loadsave.jl:235
 [4] show(::Base64.Base64EncodePipe, ::MIME{Symbol("image/png")}, ::Array{RGB{Normed{UInt8,8}},2}; minpixels::Int64, maxpixels::Int64, mapi::Function) at C:\Users\avik\.julia\packages\ImageShow\9kpaq\src\showmime.jl:43
 [5] show(::Base64.Base64EncodePipe, ::MIME{Symbol("image/png")}, ::Array{RGB{Normed{UInt8,8}},2}) at C:\Users\avik\.julia\packages\ImageShow\9kpaq\src\showmime.jl:28
 [6] base64encode(::Function, ::MIME{Symbol("image/png")}, ::Vararg{Any,N} where N; context::Nothing) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Base64\src\encode.jl:206
 [7] _binstringmime at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Base64\src\Base64.jl:46 [inlined]
 [8] #stringmime#6 at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Base64\src\Base64.jl:43 [inlined]
 [9] stringmime at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Base64\src\Base64.jl:43 [inlined]
 [10] display(::VSCodeServer.InlineDisplay, ::MIME{Symbol("image/png")}, ::Array{RGB{Normed{UInt8,8}},2}) at c:\Users\avik\.vscode\extensions\julialang.language-julia-insider-1.0.3\scripts\packages\VSCodeServer\src\display.jl:9
 [11] display(::VSCodeServer.InlineDisplay, ::String, ::Any) at .\multimedia.jl:214
 [12] display(::VSCodeServer.InlineDisplay, ::Array{RGB{Normed{UInt8,8}},2}) at c:\Users\avik\.vscode\extensions\julialang.language-julia-insider-1.0.3\scripts\packages\VSCodeServer\src\display.jl:133
 [13] display(::Any) at .\multimedia.jl:323
 [14] #invokelatest#1 at .\essentials.jl:712 [inlined]
 [15] invokelatest at .\essentials.jl:711 [inlined]
 [16] print_response(::IO, ::Any, ::Bool, ::Bool, ::Any) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\REPL\src\REPL.jl:161
 [17] print_response(::REPL.AbstractREPL, ::Any, ::Bool, ::Bool) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\REPL\src\REPL.jl:146
 [18] (::REPL.var"#do_respond#38"{Bool,VSCodeServer.var"#36#37"{REPL.LineEditREPL,REPL.LineEdit.Prompt},REPL.LineEditREPL,REPL.LineEdit.Prompt})(::Any, ::Any, ::Any) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\REPL\src\REPL.jl:729
 [19] #invokelatest#1 at .\essentials.jl:712 [inlined]
 [20] invokelatest at .\essentials.jl:711 [inlined]
 [21] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\REPL\src\LineEdit.jl:2354
 [22] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\REPL\src\REPL.jl:1055
 [23] run_repl(::REPL.AbstractREPL, ::Any) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\REPL\src\REPL.jl:206
 [24] (::Base.var"#764#766"{Bool,Bool,Bool,Bool})(::Module) at .\client.jl:383
 [25] #invokelatest#1 at .\essentials.jl:712 [inlined]
 [26] invokelatest at .\essentials.jl:711 [inlined]
 [27] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at .\client.jl:367
 [28] exec_options(::Base.JLOptions) at .\client.jl:305
 [29] _start() at .\client.jl:484
```

Things work correctly on the REPL in the terminal. Also, things work if output is supressed with a semicolon in the VSCode repl. 

Not sure if this should be reported here or in FileIO.

**Comment by johnnychen94** [comment] 2020-09-03 15:37
could possibly be fixed by https://github.com/JuliaIO/ImageIO.jl/pull/7, could you help verify with that branch?

cc: @ianshmean

**Comment by wiz21b** [comment] 2020-09-10 09:45
Hello, I'm very new to Julia, but I think I have something similar. Using pluto notebook on Debian, this :
```
using Images, ImageIO
img = load("/home/stefan/Dropbox/demo2/data/eyes.png")
```

fails with this

```
Failed to show value:

MethodError: no method matching save(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Array{ColorTypes.RGBA{FixedPointNumbers.Normed{UInt8,8}},2}, ::Pair{Symbol,ImageShow.var"#14#16"})

Closest candidates are:

save(::IO, ::S; compression_level, compression_strategy, filters, palette) where {T, S<:Union{AbstractArray{T,3}, AbstractArray{T,2} where T}} at /home/stefan/.julia/packages/PNGFiles/Sgsmw/src/io.jl:278

save(!Matched::String, ::S; compression_level, compression_strategy, filters, palette) where {T, S<:Union{AbstractArray{T,3}, AbstractArray{T,2} where T}} at /home/stefan/.julia/packages/PNGFiles/Sgsmw/src/io.jl:246

    handle_error(::MethodError, ::FileIO.Stream{FileIO.DataFormat{:PNG},IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}})@error_handling.jl:82
    handle_exceptions(::Array{Any,1}, ::String)@error_handling.jl:77
    #save#31(::Base.Iterators.Pairs{Symbol,ImageShow.var"#14#16",Tuple{Symbol},NamedTuple{(:mapi,),Tuple{ImageShow.var"#14#16"}}}, ::typeof(FileIO.save), ::FileIO.Formatted, ::Any)@loadsave.jl:235
    #show#13(::Int64, ::Int64, ::Function, ::typeof(show), ::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::MIME{Symbol("image/png")}, ::Array{ColorTypes.RGBA{FixedPointNumbers.Normed{UInt8,8}},2})@showmime.jl:43
    show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::MIME{Symbol("image/png")}, ::Array{ColorTypes.RGBA{FixedPointNumbers.Normed{UInt8,8}},2})@showmime.jl:28
    #show_richest#16(::Bool, ::typeof(Main.PlutoRunner.show_richest), ::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Any)@PlutoRunner.jl:336
    show_richest(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Any)@PlutoRunner.jl:307
    #sprint_withreturned#15(::IOContext{Base.PipeEndpoint}, ::Int64, ::typeof(Main.PlutoRunner.sprint_withreturned), ::Function, ::Array{ColorTypes.RGBA{FixedPointNumbers.Normed{UInt8,8}},2})@PlutoRunner.jl:279
    format_output(::Any)@PlutoRunner.jl:219
    formatted_result_of(::Base.UUID, ::Bool)@PlutoRunner.jl:41
    top-level scope@none:1
```

I use julia 1.5.1 and downloaded Images 0.22.4 package today (with Pkg.ad...)

The image does exists and opens without problem in other contexts.

best regards

Stéphane

**Comment by johnnychen94** [comment] 2020-09-10 10:14
Could you share the problematic image file so that we could reproduce the issue here? Or you could try

```
(v1.5) pkg> add ImageIO#ib/fix_mime
```

yourself and see if that gets fixed

**Comment by wiz21b** [comment] 2020-09-10 11:22
I've tried the fix as you've explained. Doesn''t work but the error message changed :+1: 
```
img

Failed to show value:

MethodError: no method matching lock(::PNGFiles.var"#13#14"{Int64,Int64,Int64,Nothing,IOContext{Base.GenericIOBuffer{Array{UInt8,1}}},Array{ColorTypes.RGBA{FixedPointNumbers.Normed{UInt8,8}},2},Ptr{Nothing},Ptr{Nothing}}, ::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}})

Closest candidates are:

lock(::Any, !Matched::Base.GenericCondition) at condition.jl:78

lock(::Any, !Matched::Base.AbstractLock) at lock.jl:158

lock(::Any, !Matched::WeakKeyDict) at weakkeydict.jl:76

    handle_error(::MethodError, ::FileIO.Stream{FileIO.DataFormat{:PNG},IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}})@error_handling.jl:82
    handle_exceptions(::Array{Any,1}, ::String)@error_handling.jl:77
    #save#31(::Base.Iterators.Pairs{Symbol,ImageShow.var"#14#16",Tuple{Symbol},NamedTuple{(:mapi,),Tuple{ImageShow.var"#14#16"}}}, ::typeof(FileIO.save), ::FileIO.Formatted, ::Any)@loadsave.jl:235
    #show#13(::Int64, ::Int64, ::Function, ::typeof(show), ::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::MIME{Symbol("image/png")}, ::Array{ColorTypes.RGBA{FixedPointNumbers.Normed{UInt8,8}},2})@showmime.jl:43
    show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::MIME{Symbol("image/png")}, ::Array{ColorTypes.RGBA{FixedPointNumbers.Normed{UInt8,8}},2})@showmime.jl:28
    #show_richest#16(::Bool, ::typeof(Main.PlutoRunner.show_richest), ::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Any)@PlutoRunner.jl:336
    show_richest(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Any)@PlutoRunner.jl:307
    #sprint_withreturned#15(::IOContext{Base.PipeEndpoint}, ::Int64, ::typeof(Main.PlutoRunner.sprint_withreturned), ::Function, ::Array{ColorTypes.RGBA{FixedPointNumbers.Normed{UInt8,8}},2})@PlutoRunner.jl:279
    format_output(::Any)@PlutoRunner.jl:219
    formatted_result_of(::Base.UUID, ::Bool)@PlutoRunner.jl:41
    top-level scope@none:1
```

Notice that the errors occurs only in Pluto. The julia REPL is just fine.


I attach the picture (it was produced by the Gimp application
![eyes](https://user-images.githubusercontent.com/1059519/92722893-8d3db000-f368-11ea-9b10-d2b963a6820c.png)
)

**Comment by johnnychen94** [comment] 2020-09-10 12:15
Sorry, I was unable to reproduce this.

```julia
(@v1.6) pkg> st ImageCore ImageShow TestImages FileIO ImageIO
Status `~/.julia/environments/v1.6/Project.toml`
  [5789e2e9] FileIO v1.4.3
  [a09fc81d] ImageCore v0.8.16
  [82e4d734] ImageIO v0.3.0
  [4e3cecfd] ImageShow v0.2.3
  [5e47fb64] TestImages v1.2.2
```

![image](https://user-images.githubusercontent.com/8684355/92726599-69965c00-f3a0-11ea-9989-135bf24cb247.png)

Looks like github has processed the image you uploaded. Could you share it via another way?

The new error might be related to https://github.com/JuliaIO/PNGFiles.jl/pull/19 but without a way to reproduce it, I'm not sure of it.

**Comment by johnnychen94** [comment] 2020-09-10 12:17
FYI, a workaround to this is to uninstall `ImageIO` and use the slower `ImageMagick`, `ImageIO` has to be uninstalled because it has a higher priority when loading png files.

We'd still need to fix the issue here, so it would be very kind of you to help us diagnose the issue.

**Comment by wiz21b** [comment] 2020-09-10 12:58
Ok, I'll check ImageMagick. Here's a link to my picture : https://www.dropbox.com/s/ra3hljgs0f8jm8e/eyes.png?dl=0

**Comment by wiz21b** [comment] 2020-09-10 14:52
Doing
```
import Pkg; Pkg.add("ImageMagick")
```

solved the issue. (shame on me, that was explained in the error log in the Juila repl...)

I've looked at the failing code but that's way above my current level of Julia (currently +/- 3 hours of code :-))

But if I can be of any help, I'll be glad.

**Comment by johnnychen94** [comment] 2020-12-04 07:48
closed by https://github.com/JuliaIO/PNGFiles.jl/pull/27 and https://github.com/JuliaIO/ImageIO.jl/pull/15

**Closed by johnnychen94** 2020-12-04 07:48 UTC
