### ISSUE TITLE
Certain characters in pathnames prevent images opening in imread()

### ISSUE THREAD

**Issue by cormullion** [JuliaImages/Images.jl#306] opened 2015-06-05 16:36 UTC
I'm scanning every JPG file on my iMac hard disk using Images.jl, and I encountered an error which I think is caused by an ellipsis character in a file name.

Here's a minimal example:

```
julia> cp(expanduser("~/.julia/v0.3/TestImages/images/earth_apollo17.jpg"), 
             "/tmp/its…earth_apollo17.jpg")
```

Notice the copy has an ellipsis in the name. 

The original file opens fine:

```
julia> imread(expanduser("~/.julia/v0.3/TestImages/images/earth_apollo17.jpg"))
RGB4 Image with:
  data: 3000x3002 Array{RGB4{UfixedBase{Uint8,8}},2}
  properties:
    imagedescription: <suppressed>
    spatialorder:  x y
    pixelspacing:  1 1
```

Julia finds the copy easily:

```
julia> isfile("/tmp/its…earth_apollo17.jpg")
true
```

but it doesn't open with `imread()`.

```
julia> imread("/tmp/its…earth_apollo17.jpg")
ERROR: no decode delegate for this image format `JPEG' @ error/constitute.c/ReadImage/501
 in error at error.jl:21
 in error at /Users/me/.julia/v0.3/Images/src/ioformats/libmagickwand.jl:149
 in readimage at /Users/me/.julia/v0.3/Images/src/ioformats/libmagickwand.jl:227
 in imread at /Users/me/.julia/v0.3/Images/src/io.jl:263
 in imread at /Users/me/.julia/v0.3/Images/src/io.jl:139
```

The only thing that's different is the filename.

If I rename it, it opens fine:

```
shell> mv /tmp/its…earth_apollo17.jpg /tmp/its-earth_apollo17.jpg

julia> imread("/tmp/its-earth_apollo17.jpg")
RGB4 Image with:
  data: 3000x3002 Array{RGB4{UfixedBase{Uint8,8}},2}
  properties:
    imagedescription: <suppressed>
    spatialorder:  x y
    pixelspacing:  1 1
```

(I think the original file that provoked the error was named automatically…)

**Comment by timholy** [comment] 2015-06-05 16:52
Very interesting, and thanks for the concrete instructions to reproduce. As it usually goes, however, I can't reproduce the error on my machine, so I am loathe to fix without asking you to test stuff.

First, what's your platform? Second, there is a version of `readimage` in `libmagickwand.jl` that takes an `IO` object. What happens if you change [this line](https://github.com/timholy/Images.jl/blob/f327f56ff85e21d15bf145242a8585bc2a26fdca/src/io.jl#L263) to something like
```
open(filename) do io
    LibMagick.readimage(wand, io)
end
```
(untested, but hopefully this is correct). Basically you're assuming the bug is in the ImageMagick library itself, and having julia handle the opening and closing of the file and just passing a stream object to the library.

**Comment by cormullion** [comment] 2015-06-05 17:02
Hi Tim. Thanks for the response. Gingerly I tried to do what you said (I'm on Mac OS X Yosemite), and saw this:

    julia> imread("/tmp/its…earth_apollo17.jpg")
    ERROR: `convert` has no method matching convert(::Type{Ptr{None}}, ::CFILE)
     in readimage at /Users/me/.julia/v0.3/Images/src/ioformats/libmagickwand.jl:232
     in anonymous at /Users/me/.julia/v0.3/Images/src/io.jl:266
     in open at /Applications/Julia-0.3.9.app/Contents/Resources/julia/lib/julia/sys.dylib
     in imread at /Users/me/.julia/v0.3/Images/src/io.jl:265
     in imread at /Users/me/.julia/v0.3/Images/src/io.jl:139

So at least the error message is different. (I always consider this to be progress, if not necessarily in the forwards direction.)

**Comment by timholy** [comment] 2015-06-05 17:17
Try making it `CFILE(stream).ptr` and see if that helps. `CFILE` is defined in `base/iostream.jl`.

**Comment by cormullion** [comment] 2015-06-05 18:00
Sorry, I made no progress … I'm not impatient for a fix, though, so perhaps someone with a Mac and greater competency in Julia (than me) could investigate.

**Comment by timholy** [comment] 2015-06-05 22:12
You may also want to try symlinking the file and seeing if ImageMagick can handle it then.

Also, consider reporting it as an issue to the ImageMagick developers.

**Comment by juliohm** [comment] 2017-10-02 06:28
@Evizero another one referring to the now non-existing `imread` function.

**Closed** 2017-10-02 06:31 UTC
