### ISSUE TITLE
Random artifacts in image display with IJulia 

### ISSUE THREAD

**Issue by jonasaugust** [JuliaImages/Images.jl#925] opened 2020-11-11 13:07 UTC
I sometimes get display artifacts when I display images using IJulia, and it appears to depend on the contents of the image.  The simplest example of this that I've found is a 2 pixel image, a 2x1 Float64 array [.40196 0], which should display as adjacent gray and black blocks, but instead the two blocks appear to get crushed to the left and some random vertical lines display on the right.  
Code:
```
[Gray.([.40196 0]),Gray.([.40196 0]),Gray.([.40197 0])]
```
Screen capture (Julia 1.5.2, in Debian running inside WSL2 under Windows 10, displayed on Firefox on the Windows side; the same issue appears using Edge browser, or running everything on Mac OS High Sierra with Firefox):
![juliaimages-artifact](https://user-images.githubusercontent.com/2486872/98814527-cab7cb80-23f3-11eb-8899-eb10a48ca920.PNG)
The first two instances of this image will have different such artifacts (confirming their randomness), while the last image, where the 0.40196 is very slightly increased to 0.40197, displays correctly.

**Comment by timholy** [comment] 2020-11-11 13:12
I'm not sure how IJulia manages the display, but it might be worth `pkg> add ImageIO` if you haven't done this already.

**Comment by jonasaugust** [comment] 2020-11-11 13:36
> I'm not sure how IJulia manages the display, but it might be worth `pkg> add ImageIO` if you haven't done this already.

Thanks for the suggestion.  I think I had done that at one point, but did it again anyway.  The artifacts remain.  I think image display is mediated by ImageMagick.jl, because when I removed that Julia package using ```pkg> remove ImageMagick```, I get an error (which asks for ImageMagick.jl to be added) when in IJulia I try to show a simple image using  ```Gray.(rand(2,2))```.

**Comment by timholy** [comment] 2020-11-11 16:56
Do you know what format it uses? ImageIO is better for PNG than ImageMagick, and your issue seems similar to https://github.com/JuliaIO/ImageMagick.jl/issues/184. Perhaps it's using a format not supported by ImageIO and the error is not specific to PNGs.

**Comment by johnnychen94** [comment] 2020-11-12 08:16
The same problem can be reproduced in vscode, too. If I understand it correctly, the image show pipeline is:

Colorant array ---> Base64 encoding  --> PNG encoding --> atom/vscode/Jupyter/Pluto --> HTML rendering(Base64 decoding + PNG decoding)

ImageIO does not yet support IO stream well: https://github.com/JuliaIO/PNGFiles.jl/issues/22 so `]add ImageIO` won't help in this case.

If we look at the following two results, it seems that `size(img, 2)` is improperly doubled in the first image when ImageMagick processees the image.

`Gray[0.0 0.4 0.6 0.8]` result:

![image](https://user-images.githubusercontent.com/8684355/98913280-1f496c80-2502-11eb-94a9-d3d569cd78d5.png)

`Gray[0.0 0.4 0.6 0.81]` result:

![image](https://user-images.githubusercontent.com/8684355/98913288-21133000-2502-11eb-8859-e0631566995e.png)

**Comment by johnnychen94** [comment] 2020-12-04 07:53
closed by https://github.com/JuliaIO/PNGFiles.jl/pull/27 and https://github.com/JuliaIO/ImageIO.jl/pull/15

As a side note:

ImageMagick is still problematic here, I don't know where the issue is. For image display purposes, since ImageShow will pass all the work to PNGFiles(it has a higher priority than ImageMagick), so ImageMagick will never be called in this case.

**Closed by johnnychen94** 2020-12-04 07:53 UTC
