### ISSUE TITLE
image sizes and conversion to arrays

### ISSUE THREAD

**Issue by davidbp** [JuliaImages/Images.jl#675] opened 2017-11-09 10:02 UTC
Hello,

I expected color images to be 3D arrays (or types containing a 3D array with the pixel intensities) yet I see the following:

```
img = testimage("lena_gray")
println("size: ", size(img))
img = testimage("lena")
println("size: ", size(img))

size: (256, 256)
size: (256, 256)
```

 In the case of grayscale images  ``convert(Array{Float32},img);`` works but not in the case of color images. Why?

Also ``fieldnames(img)`` returns an empty array.  And  ``methodswith(img)`` does not work. Usually it's the first thing I try when I play with an external library (besides reading the documentation).

Thank you for the hard work, the package, and documentation, looks promising.

**Comment by Evizero** [comment] 2017-11-09 10:25
how do you mean? are you expecting a separate color channel?

```julia
julia> using Images, TestImages

julia> img = testimage("lena_color_256");

julia> @show summary(img);
summary(img) = "256×256 Array{RGB{N0f8},2}"

julia> A = channelview(img);

julia> @show summary(A);
summary(A) = "3×256×256 Array{N0f8,3}"
```

Is this what you are looking for?

**Comment by Evizero** [comment] 2017-11-09 10:29
Looking at your comments about trying `fieldnames(img)`, it seems to me like you are expecting images to be some kind of special type, but it really is just a plain array with `<:Colorant` as eltype.

I wrote a small article a while back that may be helpful here https://evizero.github.io/Augmentor.jl/images/ maybe

**Comment by timholy** [comment] 2017-11-09 13:11
The augmentor link posted by @Evizero is extremely good. It sounds like you found the main JuliaImages documentation, but just in case: http://juliaimages.github.io/latest/arrays_colors.html. This explains a core abstraction: one array element = one pixel. In other languages (Matlab, Python) where you don't have this, you have to make guesses about whether this 3d array is a color image or an actual 3d volume (think biomedical imaging). That makes for some pretty horrifying code that occasionally does the wrong thing when your heuristics for guessing fail.

As far as `methodswith`, try `?Images`. See also the [function reference](http://juliaimages.github.io/latest/function_reference.html) page.

**Comment by timholy** [comment] 2017-11-09 13:13
For conversion, there is no canonical way to convert a color to `Float32`:
- did you want to do a grayscale conversion? Try `Float32.(Gray.(img))`
- did you want color channels? Try `colorchannels(img)`.

**Comment by timholy** [comment] 2017-11-17 14:19
@davidbp, if there's still something that needs fixing, please let us know. Otherwise, can you close this issue?

**Comment by davidbp** [comment] 2017-11-19 11:46
@Evizero  channelview is what I wanted. I wanted to cast an Array of a "custom" type to a 3D array of Float32 for example.

I think the documentation from [https://evizero.github.io/Augmentor.jl/images/] should be included in the package since it explains quite well some of the decisions of the package which might seem unreasonable when you start using the package.

**Closed** 2017-11-19 11:51 UTC

**Comment by timholy** [comment] 2017-11-19 13:47
> I think the documentation from [https://evizero.github.io/Augmentor.jl/images/] should be included in the package

Thanks for the response. We genuinely need input from users to figure out how to make the documentation useful. In what follows I'm going to ask you for more detail: don't take this as me arguing with you (quite the contrary), it's that I'm trying to understand what to do with this information. You might be a bit surprised how hard it is for me to understand what I should do to act on this suggestion (we all assume others can read our minds better than is actually the case).

First, what exactly do you mean by "included in the package"? We link to [JuliaImages](http://juliaimages.github.io/latest/) from the Images README. So do you mean that:
- you didn't find the JuliaImages documentation, or you didn't read it (that you learned what you needed from the augmentor page and were giving it a :+1: because it is indeed awesome)
- the JuliaImages documentation should link to the augmentor page? (Plus side: it's great! Downside: yet more to read, and users will wonder whether they should follow the link or keep reading.)
- the JuliaImages pages are missing some important information
- the JuliaImages pages are too verbose, which makes them less useful
- the JuliaImages pages are hard to understand

The reason I'm asking for more information is that you'll notice that some of these possibilities suggest edits that are in direct opposition to others (e.g., "missing" suggests we need to add more material, "too verbose" the opposite). Since you said
>  it explains quite well some of the decisions of the package which might seem unreasonable when you start using the package

it makes me wonder if the problem is verbosity/clarity, because that's what a lot of the JuliaImages documentation already does. For example, colors models and fixed point numbers are explained at  http://juliaimages.github.io/latest/arrays_colors.html#Colors-beyond-the-pale-1, and the views (like `channelview`) have their own page at http://juliaimages.github.io/latest/conversions_views.html. I can't tell from your comment if I need to add *more* material like this, condense it because it's currently too long, reduce redundancy (should I get rid of the Quickstart and just force people to read the long version?), or whether there are specific pain points that make it confusing.

The reality is that documenting a project as large as JuliaImages is a hard problem. We really, really need users to tell us (explicitly) how to make it better.

**Comment by davidbp** [comment] 2017-11-19 19:16
Hi Tim,

Your documentation is quite good and the one from `augmentator` is also very good.
In my case I read the "color separation" section from http://juliaimages.github.io/latest/conversions_views.html. For some reason, since the examples are done with "toy data" I did not pay the attention I should have. The examples use this data:
```
julia> a = reshape(collect(0.1:0.1:0.6), 3, 2)
julia> c = [RGB(a[1,j], a[2,j], a[3,j]) for j = 1:2]
```
I was looking a section with a "real image" and examples of how to get information about the image.

I ended up copy pasting information from both packages to familiarise myself with the code:
https://github.com/davidbp/learn_julia/blob/master/JuliaImages/1_images_intro.ipynb

To me having a good documentation is very important but having "executable toy examples" or "notebooks with executable examples" is also quite important. At the end of the day I end up copy pasting samples form the documentation in the REPL to better understand what is going on. Therefore, having notebooks or scripts showing what certain functions do (or how to do certain things that most people using a certain package expect) would be also very beneficial. If you want I might help you with that.

**Comment by timholy** [comment] 2017-11-20 00:17
Thanks for the feedback. I didn't realize the full importance of "big" examples (vs toys), that's extremely informative.

> Therefore, having notebooks or scripts showing what certain functions do (or how to do certain things that most people using a certain package expect) would be also very beneficial. If you want I might help you with that.

That would be awesome. I've long thought http://scikit-image.org/docs/dev/auto_examples/ might be worth emulating.

I really do like the augmentor page, I think it's probably more useful than the current Quickstart.

**Comment by Evizero** [comment] 2017-11-20 12:58
> I think it's probably more useful than the current Quickstart.

I'd say the two pages attempt different things. The slightly ironic aspect of the augmentor page is that it doesn't explain how to actually work with images at all. It is more of a gentle "this is why Images.jl is designed he way it is" blog post than anything.

If we do want to work this page into the offical docs, then I'd suggest doing it in form of a "Background and Motivation" page, with some big disclaimer that its not a usage example  (similar to the orange warning here: http://mldatapatternjl.readthedocs.io/en/latest/introduction/motivation.html)

**Comment by Evizero** [comment] 2017-11-20 14:09
To add some context. I entered the scene before the grand Images.jl redesign. During the transition I had a hard time understanding things because a.) there wasn't much documentation around and b.) I was new to image processing itself. So basically I just spend a lot of time trying things in order to figure out how and why things are the way the are. 

Once I figured all the pieces out and how they fit together, I sat down to write this article because I felt that its worth sharing how elegant and simple but powerful this design is. So rather than a "here is how you do X", I wanted to explain "Here is why Images.jl does X this way".
